jobs:
- deployment: DeployWeb
  displayName: deploy Web App
  pool:
    vmImage: 'Ubuntu-latest'
  environment: 'Prod'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo Hello world
